# --> check the technical writing for various characteristics
- midtermExam.md:
  - description: Ensure that midtermExam.md file exists in the directory
    check: ConfirmFileExists
  - description: Write a minimum number of meaningful words in the reflection
    check: CountFileWords
    options:
      count: 80
      exact: false
  # - description: Confirm that the markdown file has the correct number of headers
  #   check: CountMarkdownTags
  #   options:
  #     tag: heading
  #     count: 9
  #     exact: true
  # - description: Confirm that the markdown file has the correct number of code blocks
  #   check: CountMarkdownTags
  #   options:
  #     tag: code_block
  #     count: 4
  #     exact: true
  - description: Complete all TODOs, remove the TODO markers in the midtermExam.md
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the reflection file
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true

# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (5) in repository
  check: CountCommits
  options:
    count: 1

